# Numerical Linear Algebra
Based on Turner et al. 

We're looking at 
$$
A{\bf x}={\bf b}
$$
where $A$ is a $nxn$ matrix, and ${\bf x}$  and ${\bf b}$ are $n$-dimensional vectors. 


## Matrix operations in Python
Matrix operations are fundamental in numerical computing, and Python, with the help of the NumPy library, provides efficient and intuitive tools for working with matrices. NumPy supports a wide range of matrix operations, including addition, multiplication, transposition, inversion, and decomposition. These capabilities make it a powerful choice for scientific computing, data analysis, and machine learning tasks. In this section, we will explore how to perform basic and advanced matrix operations using NumPy.

- **Matrix addition:**  
    `C = A + A`  &nbsp;# Element-wise addition

- **Matrix multiplication:**  
    `C = A @ A`  &nbsp;# Matrix product (dot product)

- **Matrix vector multiplication:**  
    `w = A @ v`  &nbsp;# Matrix vector product (dot product)
    
- **Vector dot product:**
    `s = w @ v`  &nbsp;# Matrix vector product (dot product)

- **Transpose:**  
    `A_T = A.T`

- **Inverse:**  
    `A_inv = np.linalg.inv(A)`

- **Determinant:**  
    `det_A = np.linalg.det(A)`

- **Extract diagonal:**  
    `diag_A = np.diag(A)`

- **Solve linear system $Ax = b$:**  
    `x = np.linalg.solve(A, b)`


In [34]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Example vectors
v1 = np.array([1, 2])
v2 = np.array([3, 4])

# Matrix addition
C_add = A + B
print("Matrix Addition:\n", C_add)

# Matrix multiplication (dot product)
C_mul = A @ B
print("\nMatrix Multiplication:\n", C_mul)

# Vector addition
v_add = v1 + v2
print("\nVector Addition:", v_add)

# Dot product
v_dot = np.dot(v1, v2)
print("Dot Product:", v_dot)

# Norm of a vector
v1_norm = np.linalg.norm(v1)
print("Norm of v1:", v1_norm)

# Matrix vector multiplication
Av1 = A @ v1
print("\nMatrix-Vector Multiplication (A @ v1):", Av1)

print(f"Element-wise multiplication (A * v1):\n {A * v1}")

# Transpose
A_T = A.T
print("\nTranspose of A:\n", A_T)

# Inverse
A_inv = np.linalg.inv(A)
print("\nInverse of A:\n", A_inv)

# Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

# Extract diagonal
diag_A = np.diag(A)
print("\nDiagonal of A:", diag_A)

# Solve linear system Ax = b
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("\nSolution to Ax = b:", x)

Matrix Addition:
 [[ 6  8]
 [10 12]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Vector Addition: [4 6]
Dot Product: 11
Norm of v1: 2.23606797749979

Matrix-Vector Multiplication (A @ v1): [ 5 11]
Element-wise multiplication (A * v1):
 [[1 4]
 [3 8]]

Transpose of A:
 [[1 3]
 [2 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of A: -2.0000000000000004

Diagonal of A: [1 4]

Solution to Ax = b: [0.  0.5]


In [36]:
#help(np.linalg)

## Gauss elimination
Treated in courses in linear algebra. Here is a demonstration. 

Might have to pivot rows to avoid dividing with zero and to prevent round off errors. 

To be aware of in numerical Gaussian elimination; division by zero, round off errors, dividing with small numbers, subtracting small numbers ...

A short demonstration below. 

In [ ]:
import numpy as np

def gauss_elimination(A, b, pivoting=False,verbatim=True): # Slightly different than the code in Turner et al. 
    n = len(b) # Number of equations
    # Forward elimination
    if verbatim: print(f"Original A:\n {A}\n") # Print original matrix if verbatim is True
    for i in range(n): 
        # Partial pivoting
        max_row = np.argmax(abs(A[i:, i])) + i # Find the index of the maximum element in the current column
        if pivoting and i != max_row: # Swap rows if needed
            A[[i, max_row]] = A[[max_row, i]] # Swap rows in A
            b[[i, max_row]] = b[[max_row, i]] # Swap corresponding elements in b
        # Eliminate entries below pivot
        for j in range(i+1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]
        if verbatim: print(f"Matrix A after iteration {i+1}:\n{A}\n")
    # Back substitution
    x = np.zeros(n) # Initialize solution vector
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i] # Back substitution
    return x


In [138]:

# Example usage:
A = np.array([[1.0, 3.0, 5.0],
              [3.0, 5.0, 5.0],
              [5.0, 5.0, 5.0]])
b = np.array([9.0, 13.0, 15.0])
x = gauss_elimination(A.copy(), b.copy())
print("matrix A: \n", A)
print("vector b:    ", b)
print("\nSystem of equations:")
for i in range(A.shape[0]):
    row = " + ".join([f"{A[i, j]:>5}*x{j+1}" if A[i, j] >= 0 else f"- {abs(A[i, j]):>4}*x{j+1}" for j in range(A.shape[1])])
    print(f"Eq{i+1}: {row} = {b[i]:>5}")

print("\nSolution:")
for i, val in enumerate(x, 1):
    print(f"x{i} = {val}")
print("Solution:", x)

Original A:
 [[1. 3. 5.]
 [3. 5. 5.]
 [5. 5. 5.]]

Matrix A after iteration 1:
[[  1.   3.   5.]
 [  0.  -4. -10.]
 [  0. -10. -20.]]

Matrix A after iteration 2:
[[  1.   3.   5.]
 [  0.  -4. -10.]
 [  0.   0.   5.]]

Matrix A after iteration 3:
[[  1.   3.   5.]
 [  0.  -4. -10.]
 [  0.   0.   5.]]

matrix A: 
 [[1. 3. 5.]
 [3. 5. 5.]
 [5. 5. 5.]]
vector b:     [ 9. 13. 15.]

System of equations:
Eq1:   1.0*x1 +   3.0*x2 +   5.0*x3 =   9.0
Eq2:   3.0*x1 +   5.0*x2 +   5.0*x3 =  13.0
Eq3:   5.0*x1 +   5.0*x2 +   5.0*x3 =  15.0

Solution:
x1 = 1.0
x2 = 1.0
x3 = 1.0
Solution: [1. 1. 1.]


**Task**
Use the example code above to solve Example 3 on p. 87 in Turner 
$$
\left[\begin{array}{rrr}
7 & -7 & 1 \\
-3 & 3 & 2 \\
7 & 7 & -72 
\end{array}
\right]
\left[\begin{array}{rrr}
x \\
y\\
z
\end{array}
\right]
= 
\left[\begin{array}{rrr}
1\\
2\\
7
\end{array}
\right]
$$
with and without pivoting (change the pivoting argument in the Python cell below). What do you see?

In [ ]:

# Example usage:
A = np.array([[7,-7,1],
              [-3.0, 3.0, 2.0],
              [7.0, 7.0, -72.0]])
b = np.array([1.0, 2.0, 7.0])
x = gauss_elimination(A.copy(), b.copy(),pivoting=False) # Change the pivoting option to see what happens
print("matrix A: \n", A)
print("vector b:    ", b)
print("\nSystem of equations:")
for i in range(A.shape[0]):
    row = " + ".join([f"{A[i, j]:>5}*x{j+1}" if A[i, j] >= 0 else f"- {abs(A[i, j]):>4}*x{j+1}" for j in range(A.shape[1])])
    print(f"Eq{i+1}: {row} = {b[i]:>5}")

print("\nSolution:")
for i, val in enumerate(x, 1):
    print(f"x{i} = {val}")
print("Solution:", x)

### Hilbert matrices

Hilbert matrices are a special class of square matrices with elements given by 
$$H_{ij} = \frac{1}{i + j - 1},
$$
 where $i$ and $j$ are the row and column indices, respectively. These matrices are symmetric and positive definite, making them important in numerical analysis and linear algebra. However, Hilbert matrices are also notoriously ill-conditioned, meaning that small changes in input can lead to large errors in solutions when solving linear systems involving them. This property makes Hilbert matrices a classic example for testing the stability and accuracy of numerical algorithms.

The $5 \times 5$ Hilbert matrix:

$$
H = \begin{bmatrix}
1 & \frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \frac{1}{5} \\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \frac{1}{5} & \frac{1}{6} \\
\frac{1}{3} & \frac{1}{4} & \frac{1}{5} & \frac{1}{6} & \frac{1}{7} \\
\frac{1}{4} & \frac{1}{5} & \frac{1}{6} & \frac{1}{7} & \frac{1}{8} \\
\frac{1}{5} & \frac{1}{6} & \frac{1}{7} & \frac{1}{8} & \frac{1}{9}
\end{bmatrix}
$$

Let's do Example 6 on p. 92


In [80]:
from scipy.linalg import hilbert
import numpy as np
H=hilbert(6)
rsH = np.sum(H, axis=1)
x = gauss_elimination(H, rsH, verbatim=False)
prec=4
np.set_printoptions(precision=prec)
print(f"solution with precision {prec}: {x} ")
prec=15
np.set_printoptions(precision=prec)
print(f"solution with precision {prec}: {x} ")

solution with precision 4: [1. 1. 1. 1. 1. 1.] 
solution with precision 15: [0.999999999999228 1.000000000021937 0.999999999851792 1.00000000038537
 0.999999999574584 1.00000000016768 ] 


**Task**

Do this with a 10x10 Hilbert matrix. Do you get the same result as in the book?

### Testing the Gauss elimination routine


In [74]:
np.random.seed(42) # For reproducibility
E = np.zeros((100, 7)) # Error matrix
for n in range(4, 11): # Iterate over different system sizes
    for k in range(100):
        A = np.random.uniform(-5, 5, size=(n, n)) # Random n x n matrix
        b = np.sum(A, axis=1) # Right-hand side vector
        x = gauss_elimination(A, b,verbatim=False) # Solve system
        E[k, n-4] = np.max(np.abs(x - 1)) # Error calculation

print(f"Max error for each system size:")
for n in range(7):
    print(f"n={n+4}: {np.max(E[:, n]):.2e}, mean={np.mean(E[:, n]):.2e}, #larger than 1.e-14: {np.sum(E[:, n] > 1.e-14)}")

Max error for each system size:
n=4: 2.52e-14, mean=2.01e-15, #larger than 1.e-14: 5
n=5: 1.14e-13, mean=6.26e-15, #larger than 1.e-14: 12
n=6: 1.00e-12, mean=1.84e-14, #larger than 1.e-14: 17
n=7: 5.96e-13, mean=3.13e-14, #larger than 1.e-14: 31
n=8: 6.62e-13, mean=2.85e-14, #larger than 1.e-14: 36
n=9: 4.57e-12, mean=1.21e-13, #larger than 1.e-14: 45
n=10: 7.13e-13, mean=4.34e-14, #larger than 1.e-14: 57


## Tri-diagonal matrices
Tri-diagonal matrices are a special type of sparse matrix where nonzero elements appear only on the main diagonal, the diagonal above it, and the diagonal below it. In other words, all other entries are zero. These matrices commonly arise in the discretization of differential equations, especially in finite difference methods for solving boundary value problems. Their structure allows for highly efficient algorithms, such as the Thomas algorithm, to solve linear systems involving tri-diagonal matrices with significantly reduced computational effort compared to general dense matrices.
The one-dimensional heat equation describes how heat diffuses through a rod over time and is given by:
$$
\frac{\partial u}{\partial t} = \alpha \frac{\partial^2 u}{\partial x^2} + f(x,t)
$$
where $u(x, t)$ is the temperature at position $x$ and time $t$, and $\alpha$ is the thermal diffusivity.

### Implicit Scheme (Backward Euler)

For numerical solutions, we discretize both space and time. Let $u_j^n$ denote the temperature at position $x_j$ and time $t_n$. The implicit (backward Euler) scheme for the heat equation is:
$$
\frac{u_j^{n+1} - u_j^n}{\Delta t} = \alpha \frac{u_{j+1}^{n+1} - 2u_j^{n+1} + u_{j-1}^{n+1}}{(\Delta x)^2} + f_j^{n+1}
$$
This leads to a linear system for $u^{n+1}$ at each time step, which can be written as a tri-diagonal matrix equation:
$$
A \mathbf{u}^{n+1} = \mathbf{u}^n + \mathbf{f}^n
$$
where $A$ is a tri-diagonal matrix with main diagonal $1 + 2r$, and off-diagonals $-r$, with $r = \alpha \Delta t / (\Delta x)^2$.

The tri-diagonal structure of $A$ allows efficient solution using specialized algorithms.

**Applications:**  
Implicit methods are unconditionally stable and allow for larger time steps compared to explicit methods, making them suitable for stiff problems and long-time simulations. The tri-diagonal matrix structure arises naturally from the finite difference discretization of the second derivative in space.





# LU factorization

LU factorization is a method of decomposing a square matrix $A$ into the product of a lower triangular matrix $L$ and an upper triangular matrix $U$, such that $A = LU$. This technique simplifies the process of solving systems of linear equations, computing determinants, and inverting matrices. LU factorization is widely used in numerical linear algebra due to its efficiency and stability, especially for large systems.

LU factorization allows us to efficiently solve multiple systems of linear equations with the same coefficient matrix $A$ but different right-hand sides $b$. Once $A$ is decomposed into $L$ and $U$, we can solve $Ax = b$ by first solving $Ly = b$ (forward substitution) and then $Ux = y$ (back substitution), which is computationally cheaper than performing Gaussian elimination for each new $b$. This is especially useful in applications such as simulations, optimization, and engineering problems where the same system structure is reused with varying inputs.

### LU factorization and Gaussian elimination 
LU factorization and Gaussian elimination are fundamentally connected methods for solving linear systems.

- **Gaussian elimination** systematically applies row operations to reduce a matrix $A$ to upper triangular form $U$. Each elimination step can be represented by multiplying $A$ by an elementary lower triangular matrix $M_i$:
    $$
    M_{n-1} \cdots M_2 M_1 A = U
    $$
    where each $M_i$ eliminates entries below the diagonal in column $i$.

- **LU factorization** rewrites $A$ as the product of a lower triangular matrix $L$ and an upper triangular matrix $U$:
    $$
    A = LU
    $$
    Here, $L$ is constructed from the inverses of the elimination matrices:
    $$
    L = M_1^{-1} M_2^{-1} \cdots M_{n-1}^{-1}
    $$
    and $U$ is the final upper triangular matrix from elimination.

**Summary with matrix notation:**  
Performing Gaussian elimination is equivalent to finding matrices $L$ and $U$ such that $A = LU$. The process can be written as:
$$
A = L U \implies L^{-1}A = U
$$
where $L$ contains the multipliers used during elimination (below the diagonal), and $U$ is the result of the elimination (upper triangular). This decomposition allows us to solve $A\mathbf{x} = \mathbf{b}$ efficiently by first solving $L\mathbf{y} = \mathbf{b}$ wrt $\mathbf{y}$ (forward substitution), then $U\mathbf{x} = \mathbf{y}$ wrt $\mathbf{x}$ (back substitution).

**In case of pivoting:**  
$$
PA=LU \Rightarrow PA\mathbf{x} = LU \mathbf{x} = Pb
$$
we need to pivot the right hand side as well:
$$
 L U \mathbf{x}= P\mathbf{b} 
$$

**Note** scipy.linalg.lu returns $A=PLU$, but we know that $P^T=P^{-1}$. 


In [154]:
from scipy.linalg import lu
A=[[1,2,3],[4,5,6],[7,8,9]]
# Perform LU factorization of matrix A
P, L, U = lu(A)

print("Matrix A:")
print(A)
print("\nPermutation matrix P:")
print(P)
print("\nLower triangular matrix L:")
print(L)
print("\nUpper triangular matrix U:")
print(U)

# Verify the factorization: P @ A = L @ U
print("\nCheck: A == P @ L @ U ?")
print(np.allclose( A, P @L @ U))
print( A== P @L @ U)
print("\nP @ L @ U:")
print(P @ L @ U)    

Matrix A:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Permutation matrix P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Lower triangular matrix L:
[[1.                0.                0.               ]
 [0.142857142857143 1.                0.               ]
 [0.571428571428571 0.5               1.               ]]

Upper triangular matrix U:
[[ 7.                 8.                 9.               ]
 [ 0.                 0.857142857142857  1.714285714285714]
 [ 0.                 0.                -0.               ]]

Check: A == P @ L @ U ?
True
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

P @ L @ U:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


**Tasks**
Do LU factorization the $A$ matrix in Example 3 on p. 87 in Turner using _scipy.linalg.lu_, then solve the system with forward and backward substitution. Solve the system using Gaussian elimination. Time the LU factorization, the forward and backward substitution and the Gaussian elimination solver. The problem is.  
$$
\left[\begin{array}{rrr}
7 & -7 & 1 \\
-3 & 3 & 2 \\
7 & 7 & -72 
\end{array}
\right]
\left[\begin{array}{rrr}
x \\
y\\
z
\end{array}
\right]
= 
\left[\begin{array}{rrr}
1\\
2\\
7
\end{array}
\right]
$$


In [161]:
#Your code goes here. 

**Task:** Timing the routines

The following algorithm produces a diagonal dominant random matrix of dimension 5x5 and a right had side $b$ that is equal to the sum of the corresponding rows in $A$. 

- n=5 
- np.random.seed(42) # For reproducibility
- A = 10 * np.eye(n) # Diagonal matrix
- A += np.random.rand(n, n)
- b = np.sum(A, axis=1)

Make a loop with increasing dimensions, $n$. For each $n$, solve the resulting problem using 
    a) Gaussian elimination, 
    b) use scipy to calculate the LU factorization of A, 
    c) and thereafter use the LU factorization to solve the problem using forward and backward substitution. 
    
Time each of these and see how the time changes with increasing $n$. 

In [ ]:
import time

n=5 
np.random.seed(42) # For reproducibility
A = 10 * np.eye(n) # Diagonal matrix
A += np.random.rand(n, n)
b = np.sum(A, axis=1)

# You do the rest.  

# Iterative methods. 
Iterative methods are algorithms used to solve systems of linear equations by generating a sequence of approximations that converge to the exact solution. Unlike direct methods (such as Gaussian elimination), which attempt to solve the system in a finite number of steps, iterative methods start with an initial guess and improve it through repeated updates. 

We need iterative methods because they are often more efficient and practical for large, sparse, or structured systems where direct methods become computationally expensive or require excessive memory. Iterative techniques, such as the Jacobi and Gauss-Seidel methods, are especially useful in scientific computing, engineering simulations, and when dealing with matrices that arise from discretizing partial differential equations. They can exploit matrix sparsity, are easier to parallelize, and can provide approximate solutions quickly when high precision is not required.

### Jacobi Method Equations

Given a linear system $A\mathbf{x} = \mathbf{b}$, the Jacobi method updates each component of $\mathbf{x}$ iteratively as follows:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left( b_i - \sum_{\substack{j=1 \\ j \neq i}}^{n} a_{ij} x_j^{(k)} \right), \quad i = 1, 2, \ldots, n
$$

where:
- $x_i^{(k+1)}$ is the new value of the $i$-th variable at iteration $k+1$,
- $a_{ii}$ is the diagonal element of $A$,
- $b_i$ is the $i$-th entry of $\mathbf{b}$,
- $a_{ij}$ are the off-diagonal elements of $A$,
- $x_j^{(k)}$ are the values from the previous iteration.

All updates for $x_i^{(k+1)}$ use only the values from the previous iteration $k$. This makes the Jacobi method easy to parallelize.

In matrix-vector form, the Jacobi iteration can be written as:

$$
\mathbf{x}^{(k+1)} = D^{-1} \left( \mathbf{b} - (L + U)\mathbf{x}^{(k)} \right)
$$

where $A = D + L + U$ with:
- $D$ the diagonal part of $A$,
- $L$ the strictly lower triangular part,
- $U$ the strictly upper triangular part.

This shows that each new iterate $\mathbf{x}^{(k+1)}$ is computed using only the previous iterate $\mathbf{x}^{(k)}$.

In [ ]:
def jacobi (A , b , Nits ) :  # Jacobi method
    """ Function for computing  Nits  iterations 
    of the Jacobi method for Ax=b 
    where A  must be square matrix.  """
    D = np . diag ( A ) # Extract diagonal
    n = A . shape [0]
    A_D = A - np . diag ( D ) # This is L+U
    x = np . zeros ( n ) # Initial guess
    s = np . zeros ( ( n , Nits ) ) # Store all iterations
    for k in range ( Nits ) :
        x = ( b - A_D . dot ( x ) ) / D
        s [: , k] = x
    return s

In [135]:
dim=3
np.random.seed(42) # For reproducibility
A = 10 * np.eye(dim) # Diagonal matrix
A += np.random.rand(dim, dim)
b = np.sum(A, axis=1)
print(f"A:\n{A}")
S = jacobi(A, b, 6)
print(f"S:\n{S.T}")
print(f"S.shape:\n{S.shape}")

A:
[[10.374540118847362  0.950714306409916  0.731993941811405]
 [ 0.598658484197037 10.156018640442436  0.155994520336203]
 [ 0.058083612168199  0.866176145774935 10.60111501174321 ]]
S:
[[1.16219593629643  1.074305988522719 1.087185145800164]
 [0.987039159004468 0.989100022136149 0.993040071678878]
 [1.001489934983541 1.000870895221589 1.000961607648404]
 [0.999852343959151 0.999897403915889 0.999920679148258]
 [1.000014998442928 1.000009922112531 1.000009191738493]
 [0.999998442206494 0.999998974715751 0.999999107125909]]
S.shape:
(3, 6)


In [134]:
errors = np.linalg.norm(A @ S - b[:, None], axis=0)
for i, err in enumerate(errors):
    print(f"Iteration {i+1}: error = {err}")

Iteration 1: error = 2.246560997625002
Iteration 2: error = 0.2093305160845364
Iteration 3: error = 0.022542288300438085
Iteration 4: error = 0.0022436253150079624
Iteration 5: error = 0.00023085368550226017
Iteration 6: error = 2.3610369329478668e-05


### Gauss-Seidel Method Equations

The Gauss-Seidel method is an iterative technique for solving a linear system $A\mathbf{x} = \mathbf{b}$. It improves upon the Jacobi method by using the most recently updated values as soon as they are available.

The update rule for each component $x_i$ at iteration $k+1$ is:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left( b_i - \sum_{j=1}^{i-1} a_{ij} x_j^{(k+1)} - \sum_{j=i+1}^n a_{ij} x_j^{(k)} \right), \quad i = 1, 2, \ldots, n
$$

- $x_i^{(k+1)}$ uses the latest values $x_j^{(k+1)}$ for $j < i$ (already updated in the current iteration).
- $x_j^{(k)}$ for $j > i$ are from the previous iteration.

**Key points:**
- The method converges faster than Jacobi for many problems, especially when $A$ is diagonally dominant or symmetric positive definite.
- Each new value is immediately used in subsequent calculations within the same iteration.

In **matrix-vector form**, the Gauss-Seidel iteration can be written as:

$$
\mathbf{x}^{(k+1)} = -(D+L)^{-1} U\,\mathbf{x}^{(k)} + (D+L)^{-1}\mathbf{b}=G_{GS}\mathbf{x}^{(k)}+\mathbf{c}
$$
where $A = D + L + U$ with:
- $D$ the diagonal of $A$,
- $L$ the strictly lower triangular part,
- $U$ the strictly upper triangular part.

This equation shows that each new iterate $\mathbf{x}^{(k+1)}$ uses the latest available values for the lower part and previous values for the upper part.


In [136]:
def gauss_seidel(A, b, Nits):
    """Performs Nits iterations of the Gauss-Seidel method for Ax=b."""
    n = A.shape[0]
    x = np.zeros(n)
    s = np.zeros((n, Nits))
    for k in range(Nits):
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x[i+1:])
            x[i] = (b[i] - sum1 - sum2) / A[i, i]
        s[:, k] = x
    return s

# Demonstration with the same A and b as before
S_gs = gauss_seidel(A, b, 6)
print("Gauss-Seidel iterations (columns are successive approximations):")
print(S_gs)

Gauss-Seidel iterations (columns are successive approximations):
[[1.16219593629643  0.999564718822089 0.999995831218039 0.999999975411345
  0.999999999867319 0.9999999999993  ]
 [1.005798979802532 1.000046585678367 1.000000267566598 1.000000001434371
  1.000000000007552 1.00000000000004 ]
 [0.998637514655969 0.999998578574028 1.000000000978964 1.000000000017525
  1.00000000000011  1.000000000000001]]


In [137]:
errors_gs = np.linalg.norm(A @ S_gs - b[:, None], axis=0)
for i, err in enumerate(errors_gs):
    print(f"Iteration {i+1}: error = {err}")

Iteration 1: error = 1.6944005300073743
Iteration 2: error = 0.004477629499036153
Iteration 3: error = 4.2994672271196375e-05
Iteration 4: error = 2.537195270839496e-07
Iteration 5: error = 1.3692469708357727e-09
Iteration 6: error = 7.222688971441994e-12


## Eigenvalues
Eigenvalues are fundamental quantities associated with a square matrix that provide deep insight into its structure and behavior. For a given $n \times n$ matrix $A$, an eigenvalue $\lambda$ and a corresponding nonzero vector $\mathbf{v}$ (called an eigenvector) satisfy the equation
$$
A\mathbf{v} = \lambda \mathbf{v}.
$$
This means that applying the matrix $A$ to the vector $\mathbf{v}$ simply scales $\mathbf{v}$ by the factor $\lambda$, without changing its direction. Eigenvalues play a crucial role in many areas of mathematics, physics, and engineering, including stability analysis, vibrations, quantum mechanics, and principal component analysis. They are also central to understanding the long-term behavior of dynamical systems and are used in matrix diagonalization and decomposition techniques. The set of all eigenvalues of a matrix is called its spectrum. Previously we talked about the _spectral radius_, the largest absolute value
of the eigenvalues of a matrix. The **spectral radius** $\rho(A)$ of a matrix $A$ is defined as
$$
\rho(A) = \max \{ |\lambda| : \lambda \text{ is an eigenvalue of } A \}
$$
That is, it is the largest absolute value among all the eigenvalues of $A$. The spectral radius is important in determining the stability of iterative methods and dynamical systems. For example, in iterative solvers, convergence is guaranteed if the spectral radius of the iteration matrix is less than 1.

### Condition Numbers and Ill-Conditioned Matrices

The **condition number** of a matrix is a measure of how sensitive the solution of a linear system is to small changes or errors in the input data. For a square matrix $A$, the condition number with respect to inversion (in the 2-norm) is defined as:

For symmetric positive definite matrices, the condition number can also be expressed as the ratio of the largest to the smallest eigenvalue:
$$
\kappa(A) = \frac{|\lambda_{\max}|}{|\lambda_{\min}|}
$$
where $\lambda_{\max}$ and $\lambda_{\min}$ are the largest and smallest (in absolute value) eigenvalues of $A$. This form highlights the connection between the condition number and the spectrum of the matrix. If the smallest eigenvalue is close to zero, the matrix is nearly singular and highly ill-conditioned.

- If $\kappa(A)$ is close to 1, the matrix is **well-conditioned**: small changes in the input or right-hand side produce small changes in the solution.
- If $\kappa(A)$ is large (much greater than 1), the matrix is **ill-conditioned**: even tiny errors in the data can cause large errors in the solution.

**Ill-conditioned matrices** are problematic in numerical computations because they amplify rounding errors and make solutions unreliable. Hilbert matrices are classic examples of ill-conditioned matrices, as their condition number grows rapidly with size.

The condition number also provides insight into the stability of algorithms: a high condition number indicates that the problem is inherently difficult to solve accurately, regardless of the algorithm used.

### The power method to find the larges eigenvalue
The **power method** is an iterative algorithm used to estimate the largest (in absolute value) eigenvalue and its corresponding eigenvector of a square matrix $A$. The method is especially useful for large matrices where computing all eigenvalues is computationally expensive.

**How it works:**
1. Start with an initial nonzero vector $\mathbf{x}_0$.
2. At each iteration, compute $\mathbf{x}_{k+1} = A\mathbf{x}_k$.
3. Normalize $\mathbf{x}_{k+1}$ to prevent overflow or underflow.
4. The sequence of vectors $\mathbf{x}_k$ converges to the eigenvector associated with the largest eigenvalue (in magnitude).
5. The Rayleigh quotient $\lambda_k = \frac{\mathbf{x}_k^T A \mathbf{x}_k}{\mathbf{x}_k^T \mathbf{x}_k}$ gives an estimate of the dominant eigenvalue.

**Algorithm steps:**
1. Choose an initial vector $\mathbf{x}_0$ (not orthogonal to the dominant eigenvector).
2. For $k = 1, 2, \ldots, N$ (until convergence):
    - $\mathbf{y}_k = A \mathbf{x}_{k-1}$
    - $\mathbf{x}_k = \mathbf{y}_k / \|\mathbf{y}_k\|$
    - $\lambda_k = \mathbf{x}_k^T A \mathbf{x}_k$
3. $\lambda_k$ approximates the largest eigenvalue, and $\mathbf{x}_k$ the corresponding eigenvector.

**Key points:**
- The method converges if $A$ has a unique eigenvalue of largest magnitude.
- The rate of convergence depends on the ratio of the largest to the second largest eigenvalue.
- The power method is simple and efficient for finding the dominant eigenvalue of large, sparse matrices.

In [163]:
def power_method(A, num_iters=1000, tol=1e-10):
    """
    Computes the largest eigenvalue and corresponding eigenvector of a square matrix A using the power method.
    Args:
        A: numpy.ndarray, square matrix
        num_iters: int, maximum number of iterations
        tol: float, convergence tolerance
    Returns:
        eigenvalue: float, largest eigenvalue
        eigenvector: numpy.ndarray, corresponding eigenvector (normalized)
    """
    A = np.array(A, dtype=float)
    n = A.shape[0]
    x = np.random.rand(n)
    x /= np.linalg.norm(x)
    eigenvalue_old = 0.0

    for _ in range(num_iters):
        x_new = A @ x
        x_new_norm = np.linalg.norm(x_new)
        if x_new_norm == 0:
            raise ValueError("Encountered zero vector during iteration.")
        x = x_new / x_new_norm
        eigenvalue = x @ (A @ x)
        if np.abs(eigenvalue - eigenvalue_old) < tol:
            break
        eigenvalue_old = eigenvalue

    return eigenvalue, x