# Oppgaver for hånd

**Oppgave 1 - Repetisjon**
Løs følgende system for hånd ved hjelp av Gauss-eliminasjon uten pivotering:

$$
\begin{cases}
2x + y - z = 8 \\
-3x - y + 2z = -11 \\
-2x + y + 2z = -3
\end{cases}
$$

**Oppgave 2: Forover- og bakoverfeil**
Vi ønsker å skille mellom foroverfeil og bakoverfeil.

Gitt systemet

$$A = \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix}, \quad
b = \begin{bmatrix} 3 \\ 5 \end{bmatrix}, \quad
\tilde{x} = \begin{bmatrix} 1.0 \\ 1.3 \end{bmatrix}.$$

Hvor $\tilde{x}$ er en tilnærmet løsning.

1. Finn den eksakte løsningen x.
2. Finn foroverfeilen $||x - \tilde{x}||$.
3. Finn bakoverfeilen ved å beregne $\tilde{b} = A \tilde{x}$ og sammenligne med b.



# Oppgaver med koding

**Oppgave 3 - Øve på å løse matriser** 

Under har jeg implementert noen funksjoner for å løse et likningsstem $Ax=b$ med hjelp av Gauss-eliminasjon. 

Med hjelp av denne metoden løs følgende problemer:

a) Oppgave 1 og oppgave 2

b) En 3x3 matrise med tilfeldige koeffisienter (np.random.rand(3,3)) og en tilfeldig 3x1 vektor b (np.random.rand(3,1))


In [ ]:
import numpy as np

def gauss_forover(A, b):
    # Lager 0 nedenfor diagonalen til matrisen A
    # Returnerer den øvre triangulære systemet A og den oppdatere vektoren b

    (m,n) = np.shape(A)
    
    # Vi går kolonne for kolonne
    for i in range(m-1):  # diagonal
        diagonal = A[i, i]
        
        for j in range(i+1, m):  # radene under diagonalen
            coeff = A[j, i] / diagonal
            
            # Oppdater alle tallene i raden
            for k in range(i, n):  
                A[j, k] = A[j, k] - coeff * A[i, k]
            
            # Oppdater høyresidevektoren
            b[j] = b[j] - coeff * b[i]

    return A, b


def gauss_bakover(A, b):
    # Utfører bakover substitusjon på et øvre triangulært system.
    # Returnerer løsningen x

    (m, n) = np.shape(A)
    x = np.zeros(n)
    
    # Starter fra nederste rad og går oppover
    for i in range(m-1, -1, -1):
        # Summen av A[i,j] * x[j] for j > i
        sum_ax = 0
        for j in range(i+1, n):
            sum_ax += A[i, j] * x[j]
        
        x[i] = (b[i] - sum_ax) / A[i, i]
    
    return x

def gauss_elimansjon(A, b):
    # Gitt en matrise A og vektor b, finn løsningen x til systemet Ax=b
    # Returnerer løsningen x

    A, b = gauss_forover(A, b)
    x = gauss_bakover(A, b)

    return x

# Eksempel hvordan lage en matrise:
# A = 1  2  3
#     4  5  6
#     7  8  9

A = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
print(A)



[[1 2 3]
 [3 4 6]
 [7 8 9]]



**Oppgave 4: Swamping**
Løs systemet

$$
\begin{cases}
10^{-20}x + 2y = 1 \\
x + 2y = 4
\end{cases}
$$

a) Hva er den eksakte løsningen? 

b) Hvis du bruker metoden for Gauss-eliminasjon fra oppgave X, hva blir den tilnærmete løsningen? Hva har skjedd? 


**Oppgave 5: Gauss-eliminasjon med pivotering**

Utvid koden for Gauss-eliminasjon slik at den inkluderer partiell pivotering.
Test på systemet fra oppgave 4.

**Oppgave 6 - Tidskompleksitet gauss-eliminasjon** 

Vi skal teste tidskompleksiteten til gauss-eliminasjon. 

Anta at tiden koden tar å finne løsningen til et $NxN$ system er: $t=O(N^a)$ hvor $a$ er en konstant vi vil finne. 

Bruk koden fra oppgave 3 og gjennomfør følgende steg:

a) Definer en rekke forskjellige N-verdier (vær obs på at $N>1000$ kan ta veldig lang tid)

b) For hver N-verdi lag en tilfeldig matrise $A$ og tilfeldig vektor $b$

c) Start tidtaking og kjør metoden fra tidligere. 

d) Stopp tiden, og lagre tiden $t$ og størrelsen på matrisen $N$

e) Når du har tatt tiden for alle N'verdiene, plot verdiene i et logaritmisk diagram (plt.loglog(x,y)) og les av stigningstallet. 

Stigningstallet fra diagrammet vil være konstanten $a$. Hva betyr det for tiden det vil ta å finne løsningen til et system $Ax=b$ hvis man går fra $N=10$ til $N=100$?

**Oppgave 7 - Jacobi-iterasjon**

a) 

Løs systemet

$$
\begin{cases}
10x - y + 2z = 6 \\
-x + 11y - z = 25 \\
2x - y + 10z = -11
\end{cases}
$$

ved hjelp av Jacobi-iterasjon. Start med $x^{(0)} = (0,0,0)$ og utfør 5 iterasjoner.


b)

Prøv Jacobi på systemet:

$$
\begin{cases}
1x + 2y = 1 \\
2x + 1y = 0
\end{cases}
$$

Bruk en passende startverdi.

Hva skjer? Hvorfor får du svaret som du får? 

array([ 341., -682.])

**Oppgave 8 - Gauss-Seidel**

Løs problemene i oppgave 7 med en implementasjon av Gauss-Seidel istedet. Er det noen forskjell på løsningen etter samme antall iterasjoner? Fungerer Gauss-Seidel der Jacobi fungerer?

**Oppgave 9 - sammenligning iterative metoder**

Bruk systemet
$$
\begin{cases}
4x + y = 9 \\
x + 3y = 10
\end{cases}
$$

Start med $x^{(0)} = (0,0)$.

1. Implementer Jacobi og Gauss-Seidel.
2. Kjør begge metodene til $\|x^{(k)} - x^{(k-1)}\| < 10^{-6}$.
3. Sammenlign antall iterasjoner.